### ISSUE TITLE
Abort at "src/../high_impact/src/image.c" line 63: Failed to load image assets/sprites/blob.qoi

### ISSUE THREAD

**Issue by Starland9** [phoboslab/high_biolab#1]

**Comment by phoboslab** [comment]
How did you compile? SDL or Sokol? Is the `build/assets/sprites/blob.qoi` present? How did you run the executable? 

I assume that either the asset was not converted (should be part of `make sdl` or `make sokol` or manually with `make assets`) or you're trying to run the executable from the wrong PWD.

**Comment by Starland9** [comment]
I compile sokol
Landry Simo | Développeur chez Ovvp Corp

Le mer. 7 août 2024, 10:02, Dominic Szablewski ***@***.***> a
écrit :

**Comment by phoboslab** [comment]
Possibly related: https://github.com/phoboslab/high_biolab/pull/2

I.e. change your working directory first, before executing the binary:
```
cd build
./game_sokol
```
