### ISSUE TITLE
Feedback on building

### ISSUE THREAD

**Issue by fuhsnn** [phoboslab/high_biolab#3]
Just built the game with the homegrown C compiler I maintain; almost flawless experience! except:

- On opensuse, `zypper` by default is case-sensitive, so packages should be:
```
zypper install libX11-devel libXcursor-devel libXi-devel
```
- In the Makefile, `qoiconv` is missing `$(C_FLAGS)`, which is quite important since I need to pass `-DSTBI_NO_SIMD` to `stb_image.h`.
https://github.com/phoboslab/high_biolab/blob/47d9f4f73498c52127a5f81f4b00f54c27f2c092/Makefile#L134-L140

Thank you for the work!

**Comment by phoboslab** [comment]
That's really cool! I will fix the instructions for `zypper`, thanks for reporting.

Regarding `C_FLAGS`: I don't want to include those directly into the build command for qoiconv/qoaconv, as (depending on the platform) `C_FLAGS` also specifies libraries that are only needed for the game itself. I guess we could just put `USER_CFLAGS` in there, though!?

Not sure what the “best practice” is, when you have multiple independent binaries in one Makefile.

**Comment by fuhsnn** [comment]
Yes, `USER_CFLAGS` would do!

>Not sure what the “best practice” is

I don't know either... For defines, just prefixing subproject's options like stb does with `STB*` should go a long way, not really a big deal for simple projects.
